# This workflow builds, tests, and publishes a Node.js package to npm when a release is created.

name: Node.js Package

on:
  release:
    types: [created] # Trigger the workflow when a release is created

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run build script
      - name: Build the package
        run: npm run build

      # Step 5: Generate type definitions (if applicable)
      - name: Generate type definitions
        run: npm run types

  publish-npm:
    name: Publish to npm
    needs: build-and-test # Ensure the build-and-test job passes before publishing
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run build script
      - name: Build the package
        run: npm run build

      # Step 5: Generate type definitions (if applicable)
      - name: Generate type definitions
        run: npm run types

      # Step 6: Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
